dist: trusty
sudo: false

language: node_js
node_js:
  - '14'

addons:
  chrome: stable


cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
notifications:
 email: xskulldragon@gmail.com


deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key:
    secure: 8bc4e63c-be5a-48fb-a468-38872b00aff6
  app: gocareer
